### ISSUE TITLE
[Bugfix] Ancestry feat not showing for variant ancestry (Sylph)

### ISSUE THREAD

**Issue by thejoester** [BenABaron/pf2e-level-up-wizard#14]
First off - love this module! Especially now that it pops up when players level up! 

In my last game however we had an issue with one of my players. It was not showing the ancestry feat he was planning to take, He plays an Elf with Sylph ancestry (which is a variant and was planning on taking the [Slip with the Breeze](https://2e.aonprd.com/Feats.aspx?ID=2597) feat but it was not showing. 

The feat does have a Prerequisite that the character is expert in Athletics which he was also planning to upgrade on this level (level 5) so we tried leveling him back to 4, making him expert in athletics then leveled up again but it still was not showing. 

Here is the uuid - Compendium.pf2e.feats-srd.Item.mfy0nasMIiMLUm3f

here was the selections he had... 

![image](https://github.com/user-attachments/assets/698468ac-97d1-4295-a566-a819e813f6c2)

Looking at the [Sylph ancestry feats for level 1-5](https://2e.aonprd.com/Feats.aspx?Traits=311&values-to=level%3A5&sort=level-asc+name-asc&display=table&columns=pfs+source+rarity+trait+level+prerequisite+summary+spoilers) it looks like all of them are missing.  It appears that it is just pulling from the [Elf Ancestry feats](https://2e.aonprd.com/Feats.aspx?Traits=588&values-to=level%3A5&sort=name-asc&display=table&columns=pfs+source+rarity+trait+level+prerequisite+summary+spoilers).

**Comment by BenABaron** [comment]
Ah thank you for this! You're right, currently it's only pulling from the Elf ancestry list. I'll work on a fix for this.
