### ISSUE TITLE
[Settings] Display Wizard when Increasing Level

### ISSUE THREAD

**Issue by JDCalvert** [BenABaron/pf2e-level-up-wizard#2]
This module is looking really promising, great work! There are already a lot of buttons on character sheets, and in toolbars, added by other modules. One thing that would be great would be an option to not have the button, but to display the wizard when the character's level increases. You can hook into the PC's level increasing to detect it.

If the character's level increases by more than one, you could even queue up multiple instances of the wizard, which would really speed up making, say, a level 5 character from nothing.

**Comment by BenABaron** [comment]
Thanks JD!

Great suggestion, think this would be fairly simple to implement as an option in settings. At least single level ups, multiple may prove a little more difficult but I'll explore that as well! I'll definitely put this in the backlog for exploration

**Comment by thejoester** [comment]
Just jumping in to second this suggestion, as I use the XP awards from Monks Token bar and when a character reaches enough xp it puts in chat a link for them to "level up" which just changes the XP -1000 and increases the level. having this pop up right after would be perfect but if they then click on the wizard it tries to level them up again not pick features for the current level.

**Comment by BenABaron** [comment]
Thanks for the input joester, nice to have some additional reason to implement this. I appreciate the offer, but think I'll do this myself as a learning experience!
